#  https://platform.openai.com/docs/quickstart?desktop-os=windows
spring:
  application:
    name: backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/sandbox
    username: root
    password: ${DB_PASSWORD}

  data:
    jdbc:
      dialect: mysql

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  error:
    include-stacktrace: on_param
    include-exception: true

app:
  cors:
    allowedOrigins:
      - http://localhost
      - http://localhost:5173
      - http://localhost:4173
      - http://localhost:8080
