spring:
  application:
    name: backend
  cloud:
    azure:
      storage:
        blob:
          connection-string: ${AZURE_STORAGE_ACCOUNT}
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${AZURE_DB_HOST}.database.windows.net:1433;database=${AZURE_DB_NAME};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=60;
    username: ${AZURE_DB_USERNAME}
    password: ${AZURE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none # เปลี่ยนเป็น none หรือ ลบออกหากเป็นที่ SIT, UAT, PROD
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  error:
    include-stacktrace: on_param
    include-exception: true

app:
  cors:
    allowedOrigins:
      - http://localhost:5173
      - http://localhost:8080 # เพิ่มเผื่อกรณีคุณรัน Frontend port อื่นๆ
  api:
    prefix:
      report: v1/api/report
      supplier-order: v1/api/supplier-order

